use std::env;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR missing"));
    let web_dist = manifest_dir.join("webview-ui/dist");
    println!("cargo:rerun-if-changed={}", web_dist.display());

    let mut files = Vec::new();
    if web_dist.exists() {
        collect_files(&web_dist, &mut files);
        files.sort();
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR missing"));
    let out_path = out_dir.join("webview_assets.rs");
    let mut out = String::new();
    out.push_str("// @generated by build.rs; do not edit.\n");
    out.push_str("pub struct EmbeddedWebAsset {\n");
    out.push_str("    pub path: &'static str,\n");
    out.push_str("    pub content_type: &'static str,\n");
    out.push_str("    pub bytes: &'static [u8],\n");
    out.push_str("}\n");
    out.push_str("pub static EMBEDDED_WEB_ASSETS: &[EmbeddedWebAsset] = &[\n");

    for path in files {
        println!("cargo:rerun-if-changed={}", path.display());
        let rel = path
            .strip_prefix(&web_dist)
            .expect("dist path strip failed")
            .to_string_lossy()
            .replace('\\', "/");
        let web_path = if rel == "index.html" {
            "/index.html".to_string()
        } else {
            format!("/{}", rel)
        };
        let mime = guess_content_type(&rel);
        let rel_lit = escape_rust_string(&rel);
        let path_lit = escape_rust_string(&web_path);
        out.push_str(&format!(
            "    EmbeddedWebAsset {{ path: \"{path_lit}\", content_type: \"{mime}\", bytes: include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/webview-ui/dist/{rel_lit}\")) }},\n"
        ));
    }

    out.push_str("];\n");

    let mut file = fs::File::create(&out_path).expect("create webview_assets.rs failed");
    file.write_all(out.as_bytes())
        .expect("write webview_assets.rs failed");
}

fn collect_files(dir: &Path, files: &mut Vec<PathBuf>) {
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                collect_files(&path, files);
            } else if path.is_file() {
                files.push(path);
            }
        }
    }
}

fn escape_rust_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    for ch in value.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            _ => out.push(ch),
        }
    }
    out
}

fn guess_content_type(path: &str) -> &'static str {
    if path.ends_with(".html") {
        "text/html; charset=utf-8"
    } else if path.ends_with(".js") {
        "application/javascript; charset=utf-8"
    } else if path.ends_with(".css") {
        "text/css; charset=utf-8"
    } else if path.ends_with(".json") {
        "application/json; charset=utf-8"
    } else if path.ends_with(".svg") {
        "image/svg+xml"
    } else if path.ends_with(".png") {
        "image/png"
    } else if path.ends_with(".jpg") || path.ends_with(".jpeg") {
        "image/jpeg"
    } else if path.ends_with(".webp") {
        "image/webp"
    } else if path.ends_with(".ico") {
        "image/x-icon"
    } else {
        "application/octet-stream"
    }
}
