use sha2::{Digest, Sha256};
use std::fs::{self, File};
use std::io::{BufReader, Read};
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    let manifest_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR missing"));
    let repo_root = manifest_dir.join("../..");
    let res_dir = repo_root.join("res");
    println!("cargo:rerun-if-changed={}", res_dir.display());

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR missing"));
    let mut tar_sha256 = String::new();
    let mut tar_gz_sha256 = String::new();
    if res_dir.exists() {
        match compute_res_archive_hashes(&repo_root, &out_dir) {
            Ok((tar_hash, tar_gz_hash)) => {
                tar_sha256 = tar_hash;
                tar_gz_sha256 = tar_gz_hash;
            }
            Err(err) => {
                panic!("compute resource archive sha256 failed: {}", err);
            }
        }
    }

    let out_path = out_dir.join("embedded_resources.rs");
    let out = format!(
        "// @generated by build.rs; do not edit.\n\
#[derive(Clone, Copy)]\n\
pub struct EmbeddedResource {{\n\
    pub path: &'static str,\n\
    pub bytes: &'static [u8],\n\
}}\n\
pub static RESOURCES: &[EmbeddedResource] = &[];\n\
pub const RES_ARCHIVE_SHA256_TAR: &str = \"{tar_sha256}\";\n\
pub const RES_ARCHIVE_SHA256_TAR_GZ: &str = \"{tar_gz_sha256}\";\n"
    );
    std::fs::write(&out_path, out).expect("write embedded_resources.rs failed");
}

fn compute_res_archive_hashes(
    repo_root: &Path,
    out_dir: &Path,
) -> Result<(String, String), String> {
    let temp_dir = out_dir.join("build-res-hash");
    fs::create_dir_all(&temp_dir)
        .map_err(|err| format!("create temp dir {}: {}", temp_dir.display(), err))?;

    let tar_path = temp_dir.join("res-deterministic.tar");
    let tar_gz_path = temp_dir.join("res-deterministic.tar.gz");
    let _ = fs::remove_file(&tar_path);
    let _ = fs::remove_file(&tar_gz_path);

    let tar_status = Command::new("tar")
        .arg("--sort=name")
        .arg("--mtime=UTC 1970-01-01")
        .arg("--owner=0")
        .arg("--group=0")
        .arg("--numeric-owner")
        .arg("-C")
        .arg(repo_root)
        .arg("-cf")
        .arg(&tar_path)
        .arg("res")
        .status()
        .map_err(|err| format!("run tar failed: {}", err))?;
    if !tar_status.success() {
        return Err(format!("tar exited with non-zero status: {}", tar_status));
    }
    let tar_hash = sha256_file_hex(&tar_path)?;

    let gzip_status = Command::new("gzip")
        .arg("-n")
        .arg("-f")
        .arg("-c")
        .arg(&tar_path)
        .stdout(
            File::create(&tar_gz_path)
                .map_err(|err| format!("create {} failed: {}", tar_gz_path.display(), err))?,
        )
        .status()
        .map_err(|err| format!("run gzip failed: {}", err))?;
    if !gzip_status.success() {
        return Err(format!("gzip exited with non-zero status: {}", gzip_status));
    }
    let tar_gz_hash = sha256_file_hex(&tar_gz_path)?;

    let _ = fs::remove_file(&tar_path);
    let _ = fs::remove_file(&tar_gz_path);
    Ok((tar_hash, tar_gz_hash))
}

fn sha256_file_hex(path: &Path) -> Result<String, String> {
    let file =
        File::open(path).map_err(|err| format!("open {} failed: {}", path.display(), err))?;
    let mut reader = BufReader::new(file);
    let mut hasher = Sha256::new();
    let mut buf = [0u8; 64 * 1024];
    loop {
        let read = reader
            .read(&mut buf)
            .map_err(|err| format!("read {} failed: {}", path.display(), err))?;
        if read == 0 {
            break;
        }
        hasher.update(&buf[..read]);
    }
    Ok(to_hex(&hasher.finalize()))
}

fn to_hex(bytes: &[u8]) -> String {
    let mut out = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        out.push(nibble_to_hex(b >> 4));
        out.push(nibble_to_hex(b & 0x0f));
    }
    out
}

fn nibble_to_hex(value: u8) -> char {
    match value {
        0..=9 => (b'0' + value) as char,
        10..=15 => (b'a' + (value - 10)) as char,
        _ => '0',
    }
}
