use std::env;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR missing"));
    let res_dir = manifest_dir.join("../../res");
    println!("cargo:rerun-if-changed={}", res_dir.display());

    let mut files = Vec::new();
    if res_dir.exists() {
        collect_files(&res_dir, &mut files);
        files.sort();
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR missing"));
    let out_path = out_dir.join("embedded_resources.rs");
    let mut out = String::new();

    out.push_str("// @generated by build.rs; do not edit.\n");
    out.push_str("#[derive(Clone, Copy)]\n");
    out.push_str("pub struct EmbeddedResource {\n");
    out.push_str("    pub path: &'static str,\n");
    out.push_str("    pub bytes: &'static [u8],\n");
    out.push_str("}\n");
    out.push_str("pub static RESOURCES: &[EmbeddedResource] = &[\n");

    for path in files {
        println!("cargo:rerun-if-changed={}", path.display());
        let rel = path
            .strip_prefix(&res_dir)
            .expect("res path strip failed");
        let rel_str = rel.to_string_lossy().replace('\\', "/");
        let rel_lit = escape_rust_string(&rel_str);
        out.push_str(&format!(
            "    EmbeddedResource {{ path: \"{rel_lit}\", bytes: include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../../res/{rel_lit}\")) }},\n"
        ));
    }

    out.push_str("];\n");

    let mut file = fs::File::create(&out_path).expect("create embedded_resources.rs failed");
    file.write_all(out.as_bytes())
        .expect("write embedded_resources.rs failed");
}

fn collect_files(dir: &Path, out: &mut Vec<PathBuf>) {
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                collect_files(&path, out);
            } else if path.is_file() {
                out.push(path);
            }
        }
    }
}

fn escape_rust_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    for ch in value.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            _ => out.push(ch),
        }
    }
    out
}
